### ISSUE TITLE
OError: [Errno 2] No such file or directory: '/home/ubuntu/.docker/config.json

### ISSUE THREAD

**Issue by sudhakarVuppalapati** [awslabs/amazon-ecs-java-microservices#13]
python setup.py  -m setup -r us-west-1
INFO:__main__:Mode: setup
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
ERROR:__main__:An error occurred (AccessDenied) when calling the CreateRole operation: User: arn:aws:iam::638370140697:user/Sudhakar is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::638370140697:role/sudhakar
Traceback (most recent call last):
  File "setup.py", line 632, in <module>
    main()
  File "setup.py", line 622, in main
    setup_results = setup(project_name=project_name, service_list=service_list, region=region)
  File "setup.py", line 294, in setup
    docker_login_config()
  File "setup.py", line 252, in docker_login_config
    with open(filename, 'r+') as f:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/.docker/config.json'

Please help me what i am doing wrong.. 

I have changed "MicroECSServiceRole"  to sudhakar my name

**Comment by sudhakarVuppalapati** [comment]
setup.py  -m setup -r us-west-1
INFO:__main__:Mode: setup
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:__main__:ECS Service Role Create: arn:aws:iam::638370140697:role/sudhakar1
INFO:__main__:Task Role Create: arn:aws:iam::638370140697:role/MicroECSTaskRole
INFO:__main__:ECS Agent Role Create: arn:aws:iam::638370140697:role/MicroECSAgentRole
Traceback (most recent call last):
  File "setup.py", line 632, in <module>
    main()
  File "setup.py", line 622, in main
    setup_results = setup(project_name=project_name, service_list=service_list, region=region)
  File "setup.py", line 294, in setup
    docker_login_config()
  File "setup.py", line 252, in docker_login_config
    with open(filename, 'r+') as f:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/.docker/config.json'

**Comment by sudhakarVuppalapati** [comment]
this is the update please help me what I am doing wrong...

**Comment by mhdbashar** [comment]
You can try to login to your Docker account first to create ".docker/config.json" file
$docker longin
